modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = """
    GNU GENERAL PUBLIC LICENSE
    Version 3, 29 June 2007
"""
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId = "qfm_tools" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "QFM: Tools" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="qfm_tools.png" #optional
credits="TeamCoFH" #optional
authors = "Qboi123" #optional
description = '''
Qboi's Forge Mods: Tools

This adds tools with the materials module for the Forge Mod Series.
'''

[[dependencies.qfm_tools]] #optional
modId = "qfm_core" #mandatory
mandatory = true #mandatory
versionRange = "[2.0.1430,2.1)" #mandatory
ordering = "AFTER"
side = "BOTH"

[[dependencies.qfm_tools]] #optional
modId = "qfm_materials" #mandatory
mandatory = true #mandatory
versionRange = "[2.0.1414,2.1)" #mandatory
ordering = "AFTER"
side = "BOTH"

[[dependencies.qfm_tools]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.qfm_tools]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
