modLoader = "javafml" #mandatory
loaderVersion = "[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of version
license = """
    GNU GENERAL PUBLIC LICENSE
    Version 3, 29 June 2007
"""
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId = "qfm_updates" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "QFM: Updates" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="core.png" #optional
credits="TeamCoFH" #optional
authors = "Qboi123" #optional
description = '''
Qboi's Forge Mods: Updates

This is the debug menu mod for the Qboi's Forge Mod Series.
It adds an more advanced debug menu in the game, using the F4 button as default.
'''

[[dependencies.qfm_updates]] #optional
modId = "qfm_core" #mandatory
mandatory = true #mandatory
versionRange = "[2.0.1353,)" #mandatory
ordering = "AFTER"
side = "BOTH"

[[dependencies.qfm_updates]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.qfm_updates]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
