modLoader = "javafml"
loaderVersion = "[36,)"
license = """
    GNU GENERAL PUBLIC LICENSE
    Version 3, 29 June 2007
"""
issueTrackerURL="https://github.com/QTechCommunity/QboiForgeModSeries/issues"

[[mods]]
modId = "qfm_materials"
version = "${file.jarVersion}" # ${file.jarVersion}
displayName = "QFM: Materials"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/QTechCommunity/QboiForgeModSeries"
#logoFile="core.png" #optional
credits="TeamCoFH"
authors = "Qboi123"
description = '''
Qboi's Forge Mods: Materials

This is the debug menu mod for the Qboi's Forge Mod Series.
It adds an more advanced debug menu in the game, using the F4 button as default.
'''

[[dependencies.qfm_materials]]
modId = "qfm_core"
mandatory = true
versionRange = "[2.0.1430,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.qfm_materials]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.qfm_materials]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
